name: Scan Rules DB and Namespaces
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  scan_job:
    name: Scanner Registry Action
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Scan Registry
        uses: boostsecurityio/scanner-registry-action@8fa86a5acba13bf6806ba7d96a8d25ff9ce61f8e
        with:
          api_token: ${{ secrets.BOOST_SYSTEM_API_KEY_REGISTRY_PROD }}
